server:
  port: 8080
  servlet:
    context-path: "/api"
spring:
  application:
    name: "api-cuentas"
  profiles:
    include: dev
  datasource:
    url: "jdbc:mysql://localhost:3306/cuentasbd"
    username: "root"
    password: ""